server:
  port: 8888
  ssl:
    enabled: false
spring:
  application:
    name: FlyBy
  datasource:
    url: jdbc:postgresql://localhost:5432/flyby
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
